### ISSUE TITLE
是否可能用近似原理进行ua修改？

### ISSUE THREAD

**Issue by lucikap** [CHN-beta/rkp-ipid#4]

**Comment by CHN-beta** [comment]
？

**Comment by CHN-beta** [comment]
先关了，如果有更详细的想法的话，再开。

**Comment by lucikap** [comment]
https://github.com/lucikap/ku-ua
做了这样一个模块，但是不知道是否有效，您有空的话可以看下是否可行

**Comment by CHN-beta** [comment]
> https://github.com/lucikap/ku-ua
> 做了这样一个模块，但是不知道是否有效，您有空的话可以看下是否可行

大概看了一下内核部分的代码，大多数 UA 应该是可以修改到的。luci UI 的部分我完全不懂就没有看。

但 UA 本身是应用层的东西，所以可能会在封装 IP 包的时候被切分到两个不同的 skb 里。按照每个 skb 的 payload 是 1k 字节，ua 的长度是 100 字节估计的话，大概会有十分之一的 ua 会被这样切开，这十分之一就改不到了。这也就是我的 [xmurp](https://github.com/CHN-beta/xmurp-ua) 写得比这里的代码复杂很多而且有很多 bug 的原因，因为事情本来就挺复杂。

另外，盲目地对payload做字符串匹配然后替换的话，也有可能匹配到的不是http的头而是别的东西。实践中会不会影响什么东西我就不知道了。

我的xmurp的代码或许你可以参考一下。fork过去改或者另立门户都行。我很开心有人愿意接手我当年做了一半的工作。谢谢你。
